[package]
name = "sync"
version = "0.0.1"
authors = ["Dot HQ <contact@dothq.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3"
serde = "1.0.118"
dotenv = "0.15.0"